# Theme must be installed for this to work. Command in README!
import = [
  "~/.config/alacritty/themes/catppuchin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

